"""Build a complete test config for the between-turn effort experiment.

`router.yaml` ships with the experiment off and nothing qualified, and it
stays that way. This script reads it, lays an overlay on top, and writes a
second complete config somewhere else, so a local test instance can run
`mode: active` against one qualified Responses deployment without touching the
file the router normally serves.

What the overlay adds:

- `gpt-6-astra-responses`: the same account and the same upstream model as
  `gpt-6-astra`, declared as what the CLIProxyAPI deployment actually speaks —
  the Responses protocol, with the effort as a request field rather than a
  name suffix, and the between-turn strategy that was tested. It is a second
  model entry rather than an edit, because the suffix profile is a different
  wire contract and the two must not share one declaration.
- `astra-responses-adaptive`: a quality lane naming the three rungs, so the
  turn policy has somewhere to move inside.
- `astra-adaptive`: a strict alias that admits only that profile, opts into
  the experiment, and names an admission fallback.
- `experiments.adaptive_effort.mode: active` on that one profile.

Run it, check the result, then serve it:

    uv run python examples/make-adaptive-astra.py --out /tmp/astra.yaml \
        --sqlite /tmp/astra.db --port 18318
    uv run jev-router -c /tmp/astra.yaml check-config
    JEV_ROUTER_UPSTREAM=http://127.0.0.1:8317 \
        uv run jev-router -c /tmp/astra.yaml serve

The qualification report the profile names is resolved to an absolute path, so
the generated config validates from any working directory.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parent.parent
REPORT = REPO / "docs" / "qualification" / "2026-09-19-gpt-6-astra-cliproxyapi-responses.md"

PROFILE = "gpt-6-astra-responses"
LANE = "astra-responses-adaptive"
ALIAS = "astra-adaptive"
RULESET = "astra_adaptive"

HEADER = """\
# A test instance for the between-turn effort experiment. Generated by
# examples/make-adaptive-astra.py from router.yaml; edit that pair, not this
# file.
#
# This config declares one deployment as qualified and runs the experiment in
# `active` mode against it. Read docs/ADAPTIVE_EFFORT.md and the qualification
# report the profile names before serving it: the verdict in that report is
# provisional and covers short personal test sessions on one day, nothing
# more. router.yaml itself is unchanged, with the experiment off and nothing
# verified.
"""


def overlay(report: str) -> dict[str, Any]:
    """The blocks this test config adds to router.yaml."""
    return {
        "models": {
            PROFILE: {
                # The same account and the same upstream model as the suffix
                # profile. What differs is the wire contract: this entry
                # describes the Responses endpoint, where the effort is a
                # request field that a configuration update can move without
                # renaming the model.
                "upstream_id": "gpt-6-astra",
                "provider": "openai",
                "context_window": 400000,
                "supports_tools": True,
                "supports_vision": True,
                "efforts": ["low", "medium", "high"],
                "effort_style": "param",
                "protocol": "openai-responses",
                "max_output_tokens": 16384,
                "compatibility_revision": "responses-astra-cliproxyapi-v1",
                "tags": ["frontier", "cloud"],
                "description": (
                    "The frontier model over the Responses protocol, for the "
                    "between-turn effort experiment."
                ),
                "effort_control": {
                    "between_turn": "native_configuration_update",
                    "qualification": "verified",
                    # A separate measurement and a separate claim. Nothing in
                    # the report measured cache behaviour, so it stays
                    # unverified whatever else was observed.
                    "cache_behavior": "unverified",
                    "qualification_ref": report,
                },
            }
        },
        "quality_lanes": {
            LANE: {
                "description": (
                    "The three rungs the effort experiment may move between on "
                    "the Responses deployment."
                ),
                "qualification_ref": report,
                "qualified": [
                    {
                        "model": PROFILE,
                        "effort": effort,
                        "qualification_ref": (
                            f"{report}: the {effort} rung of the ladder the "
                            "provisional deployment test exercised"
                        ),
                    }
                    for effort in ("low", "medium", "high")
                ],
                # The safe end, not the cheap end.
                "conservative_default": {"model": PROFILE, "effort": "high"},
            }
        },
        "rulesets": {
            RULESET: {
                # One profile, so the admission rules only decide the base
                # effort the session starts at. The experiment moves it from
                # there, one rung at a time, and never moves the model.
                "low_confidence": {
                    "min_confidence": 0.4,
                    "questions": ["difficulty"],
                    "use": {"model": PROFILE, "effort": "low"},
                },
                "rules": [
                    {
                        "name": "astra_session",
                        "lane": LANE,
                        "when": {},
                        # Deliberately the bottom rung: the experiment is about
                        # whether the turn policy can raise it when a turn
                        # needs it, so starting anywhere else would hide the
                        # thing being measured.
                        "use": {"model": PROFILE, "effort": "low"},
                    }
                ],
                "default": {"model": PROFILE, "effort": "low"},
            }
        },
        "aliases": {
            ALIAS: {
                "description": (
                    "One Responses profile for the session, with the "
                    "between-turn effort experiment on."
                ),
                "session_mode": "strict",
                "adaptive_effort": True,
                "state_builder": "continuation_aware_v1",
                "questions": ["task", "difficulty", "harm_if_wrong"],
                "rules": RULESET,
                "allowed_models": [PROFILE],
                "admission_fallback": {"model": PROFILE, "effort": "low"},
            }
        },
        "experiments": {
            "adaptive_effort": {
                "mode": "active",
                "qualified_profiles": [PROFILE],
                "evaluate_on": "new_user_turn",
                "downgrade_confirmations": 2,
                "on_unknown": "keep",
                "hysteresis": True,
                "ladder": ["low", "medium", "high"],
                "ladders": {PROFILE: ["low", "medium", "high"]},
                "thresholds": {
                    "upgrade_difficulty": 1.8,
                    "upgrade_harm": 0.6,
                    "upgrade_p_hard": 0.4,
                    "corrective_followup": 0.6,
                    "downgrade_difficulty": 0.8,
                    "downgrade_harm": 0.2,
                    "quota_pressure_at": 0.6,
                    "context_safety_fraction": 0.8,
                },
                "questions": ["difficulty", "harm_if_wrong", "corrective_followup"],
                "shadow_questions": ["failure_mode"],
            }
        },
    }


def merge(base: Any, extra: Any) -> Any:
    """Add to a mapping, replace anything else. Nothing is deleted."""
    if isinstance(base, dict) and isinstance(extra, dict):
        out = dict(base)
        for key, value in extra.items():
            out[key] = merge(out[key], value) if key in out else value
        return out
    return extra


def build(source: Path, *, report: str, port: int | None, sqlite: str | None) -> dict[str, Any]:
    raw = yaml.safe_load(source.read_text()) or {}
    out = merge(raw, overlay(report))
    settings = dict(out.get("settings") or {})
    if port:
        settings["port"] = port
    if sqlite:
        # A test instance keeps its own database. Sharing router.yaml's would
        # mix an experiment's sessions into the deployment's ledger.
        settings["sqlite_path"] = sqlite
    out["settings"] = settings
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default=str(REPO / "router.yaml"))
    parser.add_argument("--out", default="-", help="where to write it, or - for stdout")
    parser.add_argument("--port", type=int, default=18318)
    parser.add_argument("--sqlite", default="~/.jev-router/adaptive-astra.db")
    parser.add_argument(
        "--report",
        default=str(REPORT),
        help="the dated deployment report this profile is qualified by",
    )
    args = parser.parse_args(argv)

    if not Path(args.report).is_file():
        print(
            f"{args.report} does not exist. An active effort profile needs a "
            "dated deployment report checked in; config load refuses it "
            "otherwise.",
            file=sys.stderr,
        )
        return 2
    config = build(
        Path(args.source), report=args.report, port=args.port, sqlite=args.sqlite
    )
    text = HEADER + yaml.safe_dump(config, sort_keys=False, width=100)
    if args.out == "-":
        sys.stdout.write(text)
    else:
        Path(args.out).expanduser().write_text(text)
        print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
